name: Test Action

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Quality Check
      id: git-quality-check
      uses: gcattan/git-quality-check@v0.1.2
      with:
        badWords: WIP, todo
        mainBranches: |
          origin/master,
          origin/develop,
          origin/main,
          origin/AddSupport3.12,
          origin/gaugup-patch-4,
          origin/gaugup-patch-3,
          origin/AddLinkCheck,
          origin/AddNBBuildStatus,
          origin/Addflake8-all-not-strings,
          origin/RefactorTestNotebooks,
          origin/ExcludeTestsFromPackaging,
          origin/RemoveDeprecatedClass,
          origin/SkipMACOS3.7Tests,
          origin/UpdateRaiUtils,
          origin/ChangeFixtureScopeToSession,
          origin/Checking-UCIAdultDataset,
          origin/AddPython3.11,
          origin/UpdateCodecovVersion,
          origin/AddflakeConfigFile,
          origin/UpdateBadges,
          origin/Remove3.6FromSetup.py,
          origin/AddMoreNumpyIntOrFloatTypes,
          origin/UpdatePythonVersionLinting,
          origin/TakeDependencyOnRaiUtils,
          origin/UpgradePythonSetupv4,
          origin/support-private-data-for-sklearn-models,
          origin/method-compat-with-dl-models,
          origin/FixLintingGate,
          origin/AddScheduledBuilds,
          origin/CorrectTypo,
          origin/AddEmptyFeaturesToVaryListValidations,
          origin/SerializeDeserializeExplainers,
          origin/CorrectVariableName,
          origin/flake8-pytest-style,
          origin/ReplaceAppendWithConcat,
          origin/UpdateCheckoutAction,
          origin/gaugup-patch-2,
          origin/LimitUnitTestPublish,
          origin/ReplaceBostonHousingDataset,
          origin/AddPython3.10,
          origin/AddMoreDesiredRangeValidations,
          origin/REmoveOldCodeCoverage,
          origin/UploadCodeCoverageCodeCov,
          origin/AddCodeAndBranchCoverageChecks,
          origin/SkipMacosTest,
          origin/AddValidationsToGenerateCounterfactuals,
          origin/RefactorDuplicateFunctions,
          origin/AddWindowsBuild-1,
          origin/AddWindowsBuild,
          origin/AddAdditionalParamsGenCF,
          origin/AddCodeQL,
          origin/FixMinorBugDiceKdTree,
          origin/RaiseExceptionWhenNoValueQueryInstance,
          origin/AddFlake8BreakPoint,
          origin/ContinueUnifyTest,
          origin/Updateflake8,
          origin/gaugup-patch-1,
          origin/AddRequirementsForLintingPackages,
          origin/CastDesiredClassToIntToFixSerialization,
          origin/AddPythonClassifiers,
          origin/SeparateLintingAndTestPipeline,
          origin/SortImportsUsingiSort,
          origin/AddCODEWONWER,
          origin/PinFlake8,
          origin/check3.5,
          origin/RaiseExceptionWhenNoCfsFound,
          origin/ImproveFeatureImpErrorMesssages,
          origin/Releasev0.7.2,
          origin/Check3.5,
          origin/ConvergePytestFixtures,
          origin/FixTabsInJsonSchema,
          origin/AddSavingCFstoDOcs,
          origin/HandleNumericCategoricalsCFGeneration,
          origin/FixDocs,
          origin/AddPython3.9Tests,
          origin/FixDiceGeneticLargeCF,
          origin/AddPytestOptionToCaptureTestRuntime,
          origin/RefactorDiplayFunctions,
          origin/AddValidationForTargetInQueryInstance,
          origin/AddTestsForDiceRandom,
          origin/AddTestsPosthocSparsityAlgorithm,
          origin/ReturnCounterfactualExplanationsConsistently,
          origin/CheckForNBCellOutput,
          origin/RunTestsInParallel,
          origin/CoalescePredictFn,
          origin/ConsolidateJsonInterfactCounterfactualExamples,
          origin/AddProgressBar,
          origin/AddMinorVersionToCounterfactualOutput,
          origin/RandomInitCF,
          origin/permitted-range,
          origin/dice-pytorch-hingeloss,
          origin/pytest-with-updated-pytorch,
          origin/feasible-cf,
          origin/cf-file-structure,
          origin/update-github-workflows
    - name: Check outputs
      run: |
        test "${{ steps.git-quality-check.outputs.score }}" != ""
